spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wang_jian_jie?characterEncoding=utf-8&useSSL=false&&serverTimezone=UTC
    #    1、serverTimezone是配置时间区域，不然启动会报错
    #    2、url 配置规则 jdbc:mysql:// + ip地址 + 端口 / 数据库名字 ? 字符编码 && 是否使用SSL && 时间区域
    #    3、useSSL MySQL在高版本需要指明是否进行SSL连接
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:

#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: false
#      hibernate.cache.region_prefix: hibernate
#      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
#      hibernate.cache.hazelcast.instance_name: AoCampaignSales
#      hibernate.cache.use_minimal_puts: true
#      hibernate.cache.hazelcast.use_lite_member: true

      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false  #ao true
      hibernate.generate_statistics: false  #生成统计日志 ao true
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true

#      hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
#      hibernate.new_generator_mappings: false
#      hibernate.format_sql: true
#      hibernate.ddl_auto: update
#      hibernate.show_sql: false    #显示sql


  elasticsearch:
    rest:
      uris: http://192.168.1.3:9090

wjj:
  name: jj