server:
  port: 8443
  # classpath就是指目录 src/main/resources/
   ssl:
       key-store: classpath:keystore.p12
       key-store-password: 123456
       keyStoreType: PKCS12
       keyAlias: tomcat

#   首先进入jdk的bin目录下，输入以下命令
#   keytool -genkey -alias tomcat  -storetype PKCS12 -keyalg RSA -keysize 2048  -keystore W:/keystore.p12 -validity 3650
#
#  输入密钥库口令:
#  再次输入新口令:
#  您的名字与姓氏是什么?
#  [Unknown]:  wang
#  您的组织单位名称是什么?
#  [Unknown]:  wang
#  您的组织名称是什么?
#  [Unknown]:  wang
#  您所在的城市或区域名称是什么?
#  [Unknown]:  shanghai
#  您所在的省/市/自治区名称是什么?
#  [Unknown]:  shanghai
#  该单位的双字母国家/地区代码是什么?
#  [Unknown]:  zh
#  CN=wang, OU=wang, O=wang, L=shanghai, ST=shanghai, C=zh是否正确?
#  [否]:  y


  #   执行命令后，在你的系统的W:/目录下会生成一个keystore.p12文件,将这个文件拷贝到我们项目resoruces目录下(和application.properties同级目录)